dataset_maker:
  type: qcs
  xml_directory: data/raw_xml/
  coder: 2
  interviews:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 16
  left_context: 1000
  right_context: 1000
  previous_question: True
  previous_question_number: True
  train_val_split: 0.8
prepare_dataset:
  span_text: True
  left_context: True
  right_context: True
  previous_question: True
  previous_question_number: True
features_to_write:
  span_text: True
  left_context: True
  right_context: True
  previous_question: True
  previous_question_number: True
output_directory: data/jsonl_data/
write_config_directory: qcs/dataset/config_instances/